### ISSUE TITLE
Fix non-isotropic half space

### ISSUE THREAD

**Issue by domna** [MarJMue/Berreman4x4#31]
Fix the eigenvalue solving and sorting for the non-isotropic half space case.

**Comment by MarJMue** [comment]
Definitely some work to do:
![newplot](https://user-images.githubusercontent.com/49639740/184325413-b4df53ff-720d-4524-b285-939299bef1f6.png)
Tried to recreate the example from [Passler and Paarmann](https://doi.org/10.1364/JOSAB.34.002128). I think the best way forward is to implement the generalized transfer matrix formalism proposed in the paper, to see where the problem is.

**Comment by MarJMue** [comment]
I found a mistake in the eigenvalue sorting and the example works now. 
It still does not include a method to resolve any occurring singularities. But i think this issue can be closed.

![newplot(2)](https://user-images.githubusercontent.com/49639740/185598332-720926bf-cffe-4e9b-8dfa-497826ba9e1f.png)
