### ISSUE TITLE
plot_mmatrix can't use any internal datastructure

### ISSUE THREAD

**Issue by MarJMue** [MarJMue/Berreman4x4#81]
The Plot function does not work with the DataFrame from the spectraray importer or with the numpy array returned from the solver.

Maybe it is also useful to include the conversion function of pycloude to use here, as both datastructures have their benefits.

**Comment by domna** [comment]
That's odd. As far as I remember I just use this function on the Dataframes in the fitting classes. I also tried to keep it generic... anyways, I'll look into it.

**Comment by MarJMue** [comment]
I digged around and found my problem. I forgot to provide the Dataframe as a List... Reading the manual would have helped...
Its not super intuitive, but I get why it is this way. I don't think we should change anything.

And I found out that the conversion function is already in the fitting submodule :+1:

**Comment by domna** [comment]
@MarJMue Maybe we can introduce a type check inside of the plot_mmatrix, so that we can supply either one data frame or a list of dataframes. This could be convenient if the function is used somewhere else. My specific design purpose was to compare fitting and experiment so I always dealt with a list of dataframes when I built it.

**Comment by domna** [comment]
I just added it. plot_mmatrix now also accepts a single dataframe instead of a list.
