### ISSUE TITLE
Extract thickness 

### ISSUE THREAD

**Issue by wlwatkins** [MarJMue/Berreman4x4#93]
Hi

I am not familiar with using ellipsometry models on delta psi data. 
looking at the docs, i understand how the library can be used to fit a model to extract n, k or eps1/2 from delta psi, but where is the estimation of the thickness (and its error) of the sample stored?

thanks

**Comment by MarJMue** [comment]
Hi,
the sample thickness is one of the parameters, that can be used to fit the experimental data with an appropriate model. A basic example can be seen [here](https://pyelli.readthedocs.io/en/latest/auto_examples/plot_02_TiO2_multilayer.html#multilayer-fit). 
There the thickness (params["TiO2_d"]) of the TiO2 layer has a start value of 20 nm and gets fitted to 24 nm (as can be seen in the fit statistics).

If you know your materials you can even use the thickness of your layer as only varying parameter. 

I hope i could help you a bit, otherwise you might have to show us the code you are using, so it's easier to help.

**Comment by wlwatkins** [comment]
So if i understand 
```
params = ParamsHist()
params.add("SiO2_n0", value=1.452, min=-100, max=100, vary=False)
params.add("SiO2_n1", value=36.0, min=-40000, max=40000, vary=False)
params.add("SiO2_n2", value=0, min=-40000, max=40000, vary=False)
params.add("SiO2_k0", value=0, min=-100, max=100, vary=False)
params.add("SiO2_k1", value=0, min=-40000, max=40000, vary=False)
params.add("SiO2_k2", value=0, min=-40000, max=40000, vary=False)
params.add("SiO2_d", value=20, min=0, max=40000, vary=True)
```

in the basic example, we set the value of 20nm as a starting point here  (SiO2_d)

and once fitted, this is the result with the fitted value ?

```
name	value	standard error	relative error	initial value	min	max	vary
SiO2_n0	1.45200000	0.00000000	(0.00%)	1.452	-100.000000	100.000000	False
SiO2_n1	36.0000000	0.00000000	(0.00%)	36.0	-40000.0000	40000.0000	False
SiO2_n2	0.00000000	0.00000000		0	-40000.0000	40000.0000	False
SiO2_k0	0.00000000	0.00000000		0	-100.000000	100.000000	False
SiO2_k1	0.00000000	0.00000000		0	-40000.0000	40000.0000	False
SiO2_k2	0.00000000	0.00000000		0	-40000.0000	40000.0000	False
SiO2_d	2.07022109	0.00714228	(0.35%)	20	0.00000000	40000.0000	True

```

**Comment by MarJMue** [comment]
Yes these are the fitted values. As you can see, the thickness changed to 2 nm with an error of 0.35%.

Edit: This is of cause only the error of the fit and does not take measurement uncertainties into account.
